"""Repository protocols — contracts without implementations.

The infrastructure layer provides concrete implementations.
The application layer depends only on these protocols (Dependency Inversion).
"""
from typing import Protocol, runtime_checkable
from uuid import UUID

from .models import User, Session, Account, Verification


@runtime_checkable
class UserRepositoryProtocol(Protocol):
    async def find_by_id(self, user_id: UUID) -> User | None: ...
    async def find_by_phone(self, phone: str) -> User | None: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> bool: ...


@runtime_checkable
class SessionRepositoryProtocol(Protocol):
    async def find_by_id(self, session_id: UUID) -> Session | None: ...
    async def find_by_hash(self, token_hash: str) -> Session | None: ...
    async def find_active_by_user(self, user_id: UUID) -> list[Session]: ...
    async def save(self, session: Session) -> Session: ...
    async def update(self, session: Session) -> Session: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


@runtime_checkable
class AccountRepositoryProtocol(Protocol):
    async def find_by_provider(
        self, provider: str, provider_account_id: str
    ) -> Account | None: ...
    async def find_by_user_id(self, user_id: UUID) -> list[Account]: ...
    async def save(self, account: Account) -> Account: ...
    async def transfer_to_user(
        self, account_id: UUID, new_user_id: UUID
    ) -> None: ...


@runtime_checkable
class VerificationRepositoryProtocol(Protocol):
    async def create(self, verification: Verification) -> Verification: ...
    async def find_valid(self, identifier: str) -> Verification | None: ...
    async def mark_verified(self, verification_id: UUID) -> None: ...
    async def increment_attempts(self, verification_id: UUID) -> int: ...


@runtime_checkable
class OTPProviderProtocol(Protocol):
    async def send_otp(self, phone: str, code: str) -> None: ...


@runtime_checkable
class GoogleTokenVerifierProtocol(Protocol):
    async def verify(self, id_token: str) -> dict: ...