// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8h1pwdo1itscZtcvwFcAWbOB04w-cmhk',
    appId: '1:411278048243:web:8fa8fcfbd5b12760897086',
    messagingSenderId: '411278048243',
    projectId: 'safarpay-70b2d',
    authDomain: 'safarpay-70b2d.firebaseapp.com',
    storageBucket: 'safarpay-70b2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMiclPUMuOp1PKstJLgS_VgFP3OBrvwZ0',
    appId: '1:411278048243:android:c8d9288059889e14897086',
    messagingSenderId: '411278048243',
    projectId: 'safarpay-70b2d',
    storageBucket: 'safarpay-70b2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMr6VafAoBwvRtg8xesMX-8G2pToxVb3I',
    appId: '1:411278048243:ios:20c52473d11480eb897086',
    messagingSenderId: '411278048243',
    projectId: 'safarpay-70b2d',
    storageBucket: 'safarpay-70b2d.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMr6VafAoBwvRtg8xesMX-8G2pToxVb3I',
    appId: '1:411278048243:ios:20c52473d11480eb897086',
    messagingSenderId: '411278048243',
    projectId: 'safarpay-70b2d',
    storageBucket: 'safarpay-70b2d.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8h1pwdo1itscZtcvwFcAWbOB04w-cmhk',
    appId: '1:411278048243:web:a82b5574e21ff609897086',
    messagingSenderId: '411278048243',
    projectId: 'safarpay-70b2d',
    authDomain: 'safarpay-70b2d.firebaseapp.com',
    storageBucket: 'safarpay-70b2d.firebasestorage.app',
  );
}
